version: "3.9"

services:
  ml-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aiml_fastapi_app
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models
      - ./data:/app/data
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
